name: CI

on: [push]
jobs:
  job:
    name: ${{ matrix.os }}-cmake-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
            
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0
      
      - name: Linux cmake
        if: matrix.os == 'ubuntu-latest'
        uses: lukka/run-cmake@v3.4
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: false
          buildDirectory: '${{ runner.workspace }}/b/ninja/'
          cmakeGenerator: Ninja
          cmakeBuildType: 'Release'
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeAppendedArgs: ' -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON"'
          buildWithCMake: true
          buildWithCMakeArgs: '--config Release --parallel'
      
      - name: Linux tests
        if: matrix.os == 'ubuntu-latest'
        shell: bash
        run: |
          #find ${{ runner.workspace }}/b;
          ${{ runner.workspace }}/b/ninja/tests
        
      - name: MacOS cmake
        if: matrix.os == 'macos-latest'
        uses: lukka/run-cmake@v3.4
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: false
          buildDirectory: '${{ runner.workspace }}/b/ninja/'
          cmakeGenerator: Ninja
          cmakeBuildType: 'Release'
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeAppendedArgs: ' -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON"'
          buildWithCMake: true
          buildWithCMakeArgs: '--config Release --parallel'
      
      - name: MacOS tests
        if: matrix.os == 'macos-latest'
        shell: bash
        run: |
          #find ${{ runner.workspace }}/b;
          ${{ runner.workspace }}/b/ninja/tests
        
      - name: Windows cmake
        if: matrix.os == 'windows-latest'
        uses: lukka/run-cmake@v3.4
        with:
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          useVcpkgToolchainFile: false
          buildDirectory: '${{ runner.workspace }}/b/ninja/'
          cmakeGenerator: Ninja
          cmakeBuildType: 'Release'
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeAppendedArgs: ' -DCMAKE_PREFIX_PATH=${{env.MINGW_BASE_DIR}} -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON"'
          buildWithCMake: true
          buildWithCMakeArgs: '--config Release --parallel'
          
      - name: Windows tests
        if: matrix.os == 'windows-latest'
        shell: powershell
        run: |
          #Get-ChildItem -Recurse -Filter '*' ${{ runner.workspace }}\b;
          ${{ runner.workspace }}\b\ninja\Release\tests.exe
